# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25fa9aaa8673b88d3ee971019ca5aa57f79ce1ecc014c842d9ad94523339c6ae84af63d73e32b1d11e7484f81c5f70b219259bd0e1918b0ed5325cc4ffcb638f

test:
  secret_key_base: 4b2e798c547be07df553ca417dd147c32843fad430ddd5397ae7a77b2cf991f48ad65d271bc3dcd55c5992aef087e8b6e0aedd0abbe1b50f554549993e59897c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
